//! Known-hosts verification for SSH connections.
//!
//! Implements Trust-On-First-Use (TOFU):
//! - On first encounter of a host:port, the server's public key is persisted
//!   and the connection is accepted.
//! - On subsequent connections, the presented key is compared to the stored
//!   key. A mismatch returns `Mismatch` (caller should refuse the connection
//!   and surface a warning); an exact match returns `Trusted`.
//!
//! Storage: `<data_dir>/ssh/known_hosts` as a plain text file, one entry per
//! line in the form:
//!
//! ```text
//! <host>:<port> <key-type> <base64-key>
//! ```
//!
//! Lines starting with `#` and empty lines are ignored. The format is
//! intentionally simple and does not attempt to be fully compatible with
//! OpenSSH's known_hosts (no hashed hostnames, no CA/revocation, no marker
//! bits). It is sufficient for a workbench-level TOFU guard against
//! accidental MITM.

use std::collections::HashMap;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::Mutex;

use anyhow::{Context, Result};
use russh::keys::ssh_key::PublicKey;

use crate::state::persistence::data_dir;

/// Decision returned by [`verify`] describing how the caller should proceed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum VerifyDecision {
    /// The host key matches a previously-stored entry — allow the connection.
    Trusted,
    /// First time seeing this host:port — the key has been persisted; allow
    /// the connection.
    AcceptedNew,
    /// The presented key does not match the stored key — **reject** the
    /// connection. The fingerprint of both keys is returned for UI display.
    Mismatch {
        stored_fingerprint: String,
        presented_fingerprint: String,
    },
}

/// In-memory cache mirroring the known_hosts file. Wrapped in a Mutex because
/// SSH connections can be established concurrently from multiple threads.
struct Cache {
    path: PathBuf,
    /// Maps "host:port" → the base64-encoded public key (without type prefix;
    /// we compare both type + key bytes via the rendered OpenSSH string).
    entries: HashMap<String, String>,
}

fn cache() -> &'static Mutex<Option<Cache>> {
    use std::sync::OnceLock;
    static CACHE: OnceLock<Mutex<Option<Cache>>> = OnceLock::new();
    CACHE.get_or_init(|| Mutex::new(None))
}

fn known_hosts_path() -> Result<PathBuf> {
    let dir = data_dir().context("data dir unavailable")?.join("ssh");
    fs::create_dir_all(&dir).ok();
    Ok(dir.join("known_hosts"))
}

/// Render a public key as `<keytype> <base64>` (single line, OpenSSH wire
/// format), suitable for exact comparison. `to_openssh()` returns an
/// OpenSSH-authorized-keys line ("type base64 [comment]"); we take the first
/// two whitespace-separated tokens so the comment (if any) is ignored.
fn key_to_string(key: &PublicKey) -> String {
    let Ok(s) = key.to_openssh() else {
        return String::new();
    };
    s.split_whitespace().take(2).collect::<Vec<_>>().join(" ")
}

/// Short fingerprint for display (default hash algorithm SHA256).
pub fn fingerprint(key: &PublicKey) -> String {
    use russh::keys::ssh_key::HashAlg;
    key.fingerprint(HashAlg::default()).to_string()
}

fn load_entries(path: &Path) -> HashMap<String, String> {
    let mut map = HashMap::new();
    let Ok(content) = fs::read_to_string(path) else {
        return map;
    };
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        // Each line: <host:port> <keytype> <base64...>
        let mut parts = line.splitn(2, ' ');
        let Some(hostport) = parts.next() else {
            continue;
        };
        let Some(rest) = parts.next() else { continue };
        map.insert(hostport.to_string(), rest.trim().to_string());
    }
    map
}

fn save_entries(path: &Path, entries: &HashMap<String, String>) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).ok();
    }
    let mut file = fs::OpenOptions::new()
        .create(true)
        .write(true)
        .truncate(true)
        .open(path)
        .with_context(|| format!("open {:?}", path))?;
    writeln!(
        file,
        "# Verve known_hosts — auto-generated by TOFU. Manual edits OK."
    )?;
    // Deterministic ordering for readable diffs.
    let mut keys: Vec<&String> = entries.keys().collect();
    keys.sort();
    for hostport in keys {
        if let Some(key) = entries.get(hostport) {
            writeln!(file, "{hostport} {key}")?;
        }
    }
    Ok(())
}

/// Verify a server public key against the known_hosts store.
///
/// See [`VerifyDecision`] for the exact return semantics. On `AcceptedNew`,
/// the key is appended to the store immediately. On `Mismatch`, the store is
/// NOT modified.
pub fn verify(host: &str, port: u16, key: &PublicKey) -> Result<VerifyDecision> {
    let hostport = format!("{host}:{port}");
    let presented = key_to_string(key);

    let mut guard = cache().lock().unwrap();
    let cache = guard.get_or_insert_with(|| {
        let path = known_hosts_path().unwrap_or_else(|_| PathBuf::from("known_hosts"));
        let entries = load_entries(&path);
        Cache { path, entries }
    });

    match cache.entries.get(&hostport) {
        Some(stored) => {
            // stored is "<keytype> <base64>", presented is the same shape.
            if stored == &presented {
                Ok(VerifyDecision::Trusted)
            } else {
                Ok(VerifyDecision::Mismatch {
                    stored_fingerprint: "(key on file)".to_string(),
                    presented_fingerprint: fingerprint(key),
                })
            }
        }
        None => {
            cache.entries.insert(hostport.clone(), presented);
            if let Err(e) = save_entries(&cache.path, &cache.entries) {
                log::warn!("known_hosts: failed to persist entry for {hostport}: {e}");
            }
            Ok(VerifyDecision::AcceptedNew)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn path_cleaning() {
        // Just verify we can build a path without panicking in test (data dir
        // may be absent in CI; accept that load returns empty).
        let _ = known_hosts_path();
    }
}
